dependencies:
  - package-lock.json
  - package.json

documentation:
  - LICENSE
  - README.md

workflow:
  - .github/workflows/*
  - .github/workflows/**/*
  - .github/dependabot.yml
  - .github/labeler.yml
  - .github/release.yml
